### ISSUE TITLE
[BUG] - Reageert niet op form clear event

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-checkbox#100]
**Omschrijf het probleem**
Een form clear event cleart de checkbox niet

**Hoe te reproduceren**
```
<form id="search-form">
<input is="vl-input-field" id="trefwoord" type="text" name="trefwoord" />
<vl-checkbox id="status-1" name="status" label="Status 1" value="status1" checked />
<vl-checkbox id="status-2" name="status" label="Status 2" value="status2" />
<button is="vl-button-link" type="reset" form="search-form">Zoekopdracht verwijderen</button>
</form>
```
Uncheck de eerste checkbox en check de tweede. Reset daarna de form. Het input veld wordt gereset maar de checkboxes niet.

**Gewenst gedrag**
Een reset event op een checkbox moet de initieel aangevinkte vakjes opnieuw aanvinken en de rest uitvinken.

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome
 - Versie component: 3.1.2

**Comment by FreekRombauts** [comment]
@coemans , getest en is het is een beetje verwarrend. Met de hier gelinkte pull request 102 (form-functions) werkt het in chrome maar niet in safari. In safari is zelfs het tonen van de labels kapot. Maar met pull request 103 (form-name-selector) werkt het zowel in chrome als in safari.

**Comment by coemans** [comment]
@FreekRombauts PR 103 werkt verder op PR 102, dus als PR 103 in orde is, zal ik beide mergen.

**Comment by coemans** [comment]
Firefox en Safari hebben helaas de ElementInternals standaard nog niet geïmplementeerd. Voorlopig onbekend wanneer deze implementatie toegevoegd zal worden. Aangezien we de PR niet onnodig willen laten afwijken van de #master, werd alvast een merge via PR #103 uitgevoerd zonder nadelige effecten in Firefox en Safari.

Indien nodig kan er een issue aangemaakt worden om op vl-form niveau de reset functie te overschrijven in afwachting.
