### ISSUE TITLE
[BUG] - Checkbox heeft geen setChecked

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-checkbox#101]
**Omschrijf het probleem**
Checkbox heeft wel een getChecked maar geen setChecked

**Hoe te reproduceren**
html:
```
<vl-checkbox name="thema" label="thema" value="thema" />
```

js:
```
let checkbox = ... // component ophalen hier
let checked = checkbox.checked // lezen werkt
checkbox.checked = true // schrijven werkt niet
```

**Gewenst gedrag**
checked state setten werkt ook.

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome
 - Versie component: 3.1.2

**Comment by coemans** [comment]
Duplicate van #52.
