### ISSUE TITLE
[BUG] - Checkbox heeft geen change event

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-checkbox#104]
**Omschrijf het probleem**
Een change event listener registreren op een vl-checkbox werkt niet.

**Hoe te reproduceren**
html:
```
<vl-checkbox name="thema" label="thema" value="thema" @change="${this.__handleChanged"></vl-checkbox>```
```
De handleChanged methode wordt niet aangeroepen als je aanvinkt. Dit gebeurt wel bij andere input elementen (vl-input, vl-select).

**Gewenst gedrag**
change events werken.

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome, safari
 - Versie component: 3.1.2

**Comment by FreekRombauts** [comment]
@coemans , net even getest en werkt in chrome. Maar dit bouwt op eerste zicht verder op de andere checkbox changes, waardoor dit ook weer niet werkt in firefox en safari.

**Comment by coemans** [comment]
De Chromium bug zal vermoedelijk in versie 87 opgelost worden, die zal waarschijnlijk november dit jaar nog uitgerold worden. Dan zal de Firefox en Safari ondersteuning verder onderzocht worden. Voorlopig ticket on hold gezien de workaround eenvoudig is.

**Comment by coemans** [comment]
@FreekRombauts de PR is vertrokken van de #master branch, dus bouwt niet verder op andere PR changes.

**Comment by FreekRombauts** [comment]
@coemans , klopt, ik was fout. Gereviewed en getest in chrome, safari en firefox. Ziet er in orde uit.
