### ISSUE TITLE
[BUG] Value wordt niet getoond bij het niet direct sluiten van de tag

### ISSUE THREAD

**Issue by umerckx** [milieuinfo/webcomponent-vl-ui-checkbox#107]
Bij volgende code wordt de value niet getoond:
```
<vl-checkbox id="environment-on-innet" data-vl-label="Ontwikkel - VS-rp-innet-sni-on-757" data-vl-value="VS-rp-innet-sni-on-757" data-vl-block="">
</vl-checkbox> 
```

Als de tag direct wordt gesloten zonder waarde, wordt de value wel getoond: 
```
<vl-checkbox id="environment-on-innet" data-vl-label="Ontwikkel - VS-rp-innet-sni-on-757" data-vl-value="VS-rp-innet-sni-on-757" data-vl-block=""></vl-checkbox>
```

**Comment by coemans** [comment]
Future @coemans probleem wordt veroorzaakt doordat slot voorrang krijgt op data-vl-label attribuut. Het lijkt een issue veroorzaakt door het niet onmiddellijk afsluiten van de tag, maar eigenlijk wordt de data-vl-label overschreven met een slot spatie. Best controle uitvoeren op empty voordat slot het data-vl-label overschrijft.
