### ISSUE TITLE
[TASK] - Informeren bij Webuniversum waarom input event gestuurd wordt en niet change event bij toggelen

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-checkbox#21]

**Comment by coemans** [comment]
Niet geïnformeerd bij Webuniversum, maar de API gelezen:
{quote}
The input event is fired every time the value of the element changes. This is unlike the change event, which only fires when the value is committed, such as by pressing the enter key, selecting a value from a list of options, and the like.
{quote}
