### ISSUE TITLE
[Feature request] - Onderzoeken of er mogelijkheid bestaat om te migreren naar native element

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-checkbox#32]
**Wat moet er gebeuren**
Bekijken of er ipv een VlElement een native HtmlInputElement kan gebruikt worden. Voordeel zou zijn dat er geen extra event zou moeten gestuurd worden die met composed door de shadow dom breekt.

**Extra info**
Zie ook multiselect als voorbeeld als er iets rond moet gewrapped worden rond de component om extra css te plaatsen hierop.

**Comment by coemans** [comment]
@Pieter-Beckers dit is eigenlijk geen feature request, maar een bug report. De bug werd geïntroduceerd in PR #17 en is nog niet gemerged naar de branch, bijgevolg hebben alleen afnemers van de branch last van deze bug. Ik stel voor dat door het team (niet UIG) een bug ticket gemaakt wordt, bijhorend dus ook een PR met een test voor regressie. Die PR zal onmiddellijk gemerged worden naar de master branch zodat nadien #17 veilig gemerged kan worden.

De oplossing van #17 introduceert dus blijkbaar een blokkerende bug en lost een probleem op dat voorlopig niet in isolatie reproduceerbaar is. Te bekijken.
