### ISSUE TITLE
[FEATURE] - Label met HTML code

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-checkbox#68]
**Wat moet er gebeuren**
In een van de mocks was het voorstel om volgend checkbox label te hebben:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/29454303/74656412-5b77b880-518e-11ea-9b4b-125838ce9f1d.png">

Met de huidige implementatie krijg je echter 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/29454303/74656513-8b26c080-518e-11ea-816c-e3254d4c0109.png">

indien de input het volgende is

`<vl-checkbox block label='<span>Ik heb de <a href="#" target="_blank">voorwaarden</a> gelezen en begrepen</span>'></vl-checkbox>`

**Extra info**
Een eenvoudige manier zou zijn door:

```
    _labelChangedCallback(oldValue, newValue) {
        this._label = newValue;
        this._checkboxLabelElement.append(this._label);
    }
```
te vervangen in:

```
    _labelChangedCallback(oldValue, newValue) {
        this._label = newValue;
        this._checkboxLabelElement.appendChild(this._template(this._label));
    }
```

Maar

- dit zal waarschijnlijk issues geven met functie __singleChangedCallback_
- willen we wel HTML code in dat label attribuut proppen

Te bekijken of dit op een proper manier (e.g. slot) kan opgelost worden

**Workaround**

Voorlopig volgende workaround gebruikt om toch een label te hebben én de tekst met link
```
<vl-checkbox label='Ik heb de voorwaarden gelezen en begrepen' single></vl-checkbox>
<span>Ik heb de <a href="#" target="_blank">voorwaarden</a> gelezen en begrepen</span>
```
De verticale alignering van de span zit echter niet goed:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/29454303/74657145-e6a57e00-518f-11ea-8a4e-ef142d09e632.png">

**Comment by philipperutten** [comment]
Deze implementatie van vl-checkbox gaat in tegen native gedrag en dus tegen het hele basisprincipe van web components ("use the platform"), niet?

**Comment by philipperutten** [comment]
Wellicht op te lossen met een slot?
