### ISSUE TITLE
[BUG] - Waarde is niet beschikbaar op de form

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-checkbox#99]
**Omschrijf het probleem**
Alle standaard form fields (input, select, ...) zijn in js beschikbaar op het form object. Maar voor vl-ui-checkbox is dit niet het geval.

**Hoe te reproduceren**
html:
```
<form id="search-form">
<input is="vl-input-field" id="trefwoord" type="text" name="trefwoord" />
<vl-checkbox name="thema" label="thema1" value="thema 1" />
</form>
```

js:
```
form = ... // hier form ref ophalen
form['trefwoord'] // haalt trefwoord input op
form['thema'] // zou thema checkbox moeten ophalen, maar dat werkt niet
```

**Gewenst gedrag**
Checkbox is beschikbaar op de form, net zoals vl-ui-input (en andere input elementen).
Moet ook werken als er meerdere checkboxes met zelfde name op de form staan.

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome / safari
 - Versie component: 3.1.2

**Comment by FreekRombauts** [comment]
@coemans , hertest maar nog niet helemaal in orde. `form['thema']` geeft nu niet meer null terug maar een RadioNodeList. Die RadioNodeList is echter altijd leeg.

**Comment by coemans** [comment]
@FreekRombauts functionaliteit werd voorzien, maar er werd geen rekening gehouden met meerdere checkbox input elementen met hetzelfde name attribuut, dat was niet helemaal duidelijk uit het voorbeeld of de beschrijving. Ik zal dit uitbreiden.

**Comment by coemans** [comment]
De huidige code zou voldoende moeten zijn om ook te werken wanneer het name attribuut bij verschillende form elementen identiek is. Ik heb dit geverifieerd bij een medewerker van de HTML SPEC. Vermoedelijk is dit een Chromium bug. Ik heb een bug report toegevoegd. Zodra er feedback is, update ik dit issue.

**Comment by FreekRombauts** [comment]
@coemans , Heb dit nog even hertest met de laatste changes die je aan de branch hebt gedaan. Zoals verwacht (wegens chromium bug) werkt het inderdaad nog steeds niet in chrome. Ik heb ook even in andere browsers getest (safari en firefox) en daar werkt het evenmin. Ik krijg daar een error bij het laden van checkboxes dat attachInternals niet gekend is.

Even verder graven doet mij vermoeden dat je de custom form element html spec gebruikt om dit te fixen. Die is zeer nieuw (zomer 2019) en heeft nog geen ondersteuning in safari en firefox.

**Comment by coemans** [comment]
De Chromium bug zal vermoedelijk in versie 87 opgelost worden, die zal waarschijnlijk november dit jaar nog uitgerold worden. Dan zal de Firefox en Safari ondersteuning verder onderzocht worden. Voorlopig ticket on hold gezien de workaround eenvoudig is.

**Comment by coemans** [comment]
De Chrome bug werd opgelost, maar Firefox en Safari hebben helaas de ElementInternals standaard nog niet geïmplementeerd. Voorlopig onbekend wanneer deze implementatie toegevoegd zal worden. Aangezien we de PR niet onnodig willen laten afwijken van de #master, werd alvast een merge uitgevoerd zonder nadelige effecten in Firefox en Safari. In afwachting kunnen er eenvoudige workarounds toegepast worden.
